name: Deploy React App to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          project_id: hack-team-yoddhas
          workload_identity_provider: projects/785558430619/locations/global/workloadIdentityPools/github-2023/providers/github-2023
          service_account: infrastructure@hack-team-yoddhas.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      # Build & push the image to Artifact Registry
      - name: Build and Push Container Image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/hack-team-yoddhas/react-apps/yoddhas-app:${GITHUB_SHA}"
          docker buildx create --use || true
          docker buildx build --no-cache --platform linux/amd64 -t $IMAGE . --push
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy yoddhas-app \
            --image $IMAGE \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
